### ISSUE TITLE
Add option on how to deal with file meta data problems

### ISSUE THREAD

**Issue by fdemello** [CiscoDevNet/webex-teams-archiver#12]
When there's a problem with the file meta data, the archiver currently raises an exception. The user should be given an option of how to deal with these:

1. Skip the file
2. Give the file a random name
3. Raise an exception

**Comment by pzystorm** [comment]
I have the same problem.

```
Traceback (most recent call last):
  File "./export.py", line 11, in <module>
    archiver.archive_room(room_id)
  File "/usr/local/lib/python3.6/dist-packages/webexteamsarchiver/webexteamsarchiver.py", line 165, in archive_room
    self._gather_room_information(room_id, download_avatars)
  File "/usr/local/lib/python3.6/dist-packages/webexteamsarchiver/webexteamsarchiver.py", line 302, in _gather_room_information
    self._organize_by_threads(self.messages, download_avatars)
  File "/usr/local/lib/python3.6/dist-packages/webexteamsarchiver/webexteamsarchiver.py", line 349, in _organize_by_threads
    file_metadata = self.file_details(url)
  File "/usr/local/lib/python3.6/dist-packages/webexteamsarchiver/webexteamsarchiver.py", line 106, in file_details
    raise MalformedResponse(message)
webexteamssdk.exceptions.MalformedResponse: Failed to find filename='' in attachment; filename="" for url https://webexapis.com/v1/contents/Y2lzY29zcGFyazovL....................tNDExZjg2MTQ0Yzg5LzA
```

When looking at the headers for that file:
```
HTTP/2 200
date: Wed, 17 Mar 2021 01:31:44 GMT
content-type: text/plain
content-length: 115732
cache-control: no-cache, no-store
via: 1.1 linkerd
trackingid: ROUTER_60.......2803BA
server: Redacted
content-disposition: attachment; filename=""
vary: accept-encoding
strict-transport-security: max-age=63072000; includeSubDomains; preload
```

so there is really no filename... how can that be?.. and is there a workaround?

**Comment by pzystorm** [comment]
FYI, I have changed this if clause:
https://github.com/CiscoDevNet/webex-teams-archiver/blob/1106086cb5387943209a47bda7000c2ee1171ccd/webexteamsarchiver/webexteamsarchiver.py#L102-L106
to this block:
```
            if not filename_re:
                newfilename = re.sub(r'^.+/([^/]+)$', r'\1', url)
                message = (
                    f"Set filename to '{newfilename}' in {r.headers.get('Content-Disposition', '')} for url {url}"
                )
                logger.debug(message)
                filename_re = re.search(r"filename=\"(.+?)\"", f"filename=\"{newfilename}\"", re.I)
                #raise MalformedResponse(message)
```

That will set the filename to the last part of the URL.
Means: the URL of the attachment is maybe something like this:
https://webexapis.com/v1/contents/Y2lzY29zcGFyazovL3VzL0NPTlRFTlQvYTM1N2foobarasdf
And if then there is no original filename information in the content-disposition header like I describe in my posting above, then the file will be saved as "Y2lzY29zcGFyazovL3VzL0NPTlRFTlQvYTM1N2foobarasdf"

Works like a charm for me.

**Comment by fdemello** [comment]
@pzystorm thanks for the suggestion! I've release v0.11.1 with this improvement.
