### ISSUE TITLE
Request time-out for a large room 

### ISSUE THREAD

**Issue by shmandal** [CiscoDevNet/webex-teams-archiver#15]
I'm trying to archive a room of mine which is 2-3 years old and is HUGE 

I get a timeout error, how can I increase the timeout? 

>>> room_id = "XXX"
>>> archiver.archive_room(room_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ws/shmandal-sjc/pyats_32/lib/python3.6/site-packages/webexteamsarchiver/webexteamsarchiver.py", line 158, in archive_room
    text_format, html_format, json_format, timestamp_format)
  File "/ws/shmandal-sjc/pyats_32/lib/python3.6/site-packages/webexteamsarchiver/webexteamsarchiver.py", line 236, in _archive
    file_metadata = self.file_details(url)
  File "/ws/shmandal-sjc/pyats_32/lib/python3.6/site-packages/webexteamsarchiver/webexteamsarchiver.py", line 91, in file_details
    r.raise_for_status()
  File "/ws/shmandal-sjc/pyats_32/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 408 Client Error: Request Time-out for url: https://api.ciscospark.com/v1/contents/Y2lzY29zcGFyazovL3VzL0NPTlRFTlQvNzAxYzkxODAtNTI0ZC0xMWU4LThlZmQtYzc1YzdjY2Y1Y2M2LzA
>>>

**Comment by fdemello** [comment]
@shmandal The code only allows you to specify the `single_request_timeout` for Webex API calls. Your traceback is from downloading files where we don't set a timeout, meaning, requests should wait indefinitely. 

> A 408 Request Timeout message is an HTTP status code that is returned to the client when a request to the server takes longer than the server's allocated timeout window. In this case, the server will terminate the connection if it is idle and thus return the 408 Request Timeout message.
